import { DarkTheme, DefaultTheme, type Theme } from '@react-navigation/native'
import { BRAND } from '@/lib/brand'

export const THEME = {
  light: {
    background: BRAND.colors.light.paper,
    foreground: BRAND.colors.light.ink,
    card: BRAND.colors.light.panel,
    cardForeground: BRAND.colors.light.ink,
    popover: BRAND.colors.light.panel,
    popoverForeground: BRAND.colors.light.ink,
    primary: BRAND.colors.light.accent,
    primaryForeground: '#FFFAF2',
    secondary: BRAND.colors.light.paperStrong,
    secondaryForeground: BRAND.colors.light.ink,
    muted: BRAND.colors.light.paperStrong,
    mutedForeground: BRAND.colors.light.muted,
    accent: BRAND.colors.light.paperStrong,
    accentForeground: BRAND.colors.light.accent,
    destructive: BRAND.colors.light.destructive,
    border: BRAND.colors.light.lineStrong,
    input: BRAND.colors.light.lineStrong,
    ring: 'rgba(180, 73, 47, 0.45)',
    radius: '0.625rem',
    chart1: BRAND.colors.light.accent,
    chart2: BRAND.colors.light.sage,
    chart3: BRAND.colors.light.ink,
    chart4: BRAND.colors.light.muted,
    chart5: BRAND.colors.light.paperStrong,
  },
  dark: {
    background: BRAND.colors.dark.paper,
    foreground: BRAND.colors.dark.ink,
    card: BRAND.colors.dark.panel,
    cardForeground: BRAND.colors.dark.ink,
    popover: BRAND.colors.dark.panel,
    popoverForeground: BRAND.colors.dark.ink,
    primary: BRAND.colors.dark.accent,
    primaryForeground: BRAND.colors.dark.paper,
    secondary: BRAND.colors.dark.paperStrong,
    secondaryForeground: BRAND.colors.dark.ink,
    muted: BRAND.colors.dark.paperStrong,
    mutedForeground: BRAND.colors.dark.muted,
    accent: BRAND.colors.dark.paperStrong,
    accentForeground: BRAND.colors.dark.accent,
    destructive: BRAND.colors.dark.destructive,
    border: BRAND.colors.dark.lineStrong,
    input: BRAND.colors.dark.lineStrong,
    ring: 'rgba(216, 106, 77, 0.45)',
    radius: '0.625rem',
    chart1: BRAND.colors.dark.accent,
    chart2: BRAND.colors.dark.sage,
    chart3: BRAND.colors.dark.ink,
    chart4: BRAND.colors.dark.muted,
    chart5: BRAND.colors.dark.paperStrong,
  },
}

export const NAV_THEME: Record<'light' | 'dark', Theme> = {
  light: {
    ...DefaultTheme,
    colors: {
      background: THEME.light.background,
      border: THEME.light.border,
      card: THEME.light.card,
      notification: THEME.light.destructive,
      primary: THEME.light.primary,
      text: THEME.light.foreground,
    },
  },
  dark: {
    ...DarkTheme,
    colors: {
      background: THEME.dark.background,
      border: THEME.dark.border,
      card: THEME.dark.card,
      notification: THEME.dark.destructive,
      primary: THEME.dark.primary,
      text: THEME.dark.foreground,
    },
  },
}
